spring:
  datasource:
    url: jdbc:mysql://db4free.net:3306/asistencia
    username: fisi_infra
    password: fi$iinfr@
  mvc:
    favicon:
      enabled: true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
